export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_SELECTED_ITEMS = "REMOVE_SELECTED_ITEMS";

export const SELECT_ALL_ITEMS = "SELECT_ALL_ITEMS";
export const SELECT_ITEM = "SELECT_ITEM";
export const UNSELECT_ALL_ITEMS = "UNSELECT_ALL_ITEMS";
