export const SET_IS_HOMEPAGE = "SET_IS_HOMEPAGE";

export const GET_RECOMMENDATION_REQUEST = "GET_RECOMMENDATION_REQUEST";
export const GET_RECOMMENDATION_SUCCESS = "GET_RECOMMENDATION_SUCCESS";
export const GET_RECOMMENDATION_FAIL = "GET_RECOMMENDATION_FAIL";

export const GET_AD_REQUEST = "GET_AD_REQUEST";
export const GET_AD_SUCCESS = "GET_AD_SUCCESS";
export const GET_AD_FAIL = "GET_AD_FAIL";

export const GET_NEW_ARRIVAL_REQUEST = "GET_NEW_ARRIVAL_REQUEST";
export const GET_NEW_ARRIVAL_SUCCESS = "GET_NEW_ARRIVAL_SUCCESS";
export const GET_NEW_ARRIVAL_FAIL = "GET_NEW_ARRIVAL_FAIL";
