export const GET_RECOMMENDATION_REQUEST = "GET_RECOMMENDATION_REQUEST";
export const GET_RECOMMENDATION_SUCCESS = "GET_RECOMMENDATION_SUCCESS";
export const GET_RECOMMENDATION_FAIL = "GET_RECOMMENDATION_FAIL";
