export const POST_STOCK_CHECK_REQUEST = "POST_STOCK_CHECK_REQUEST";
export const POST_STOCK_CHECK_SUCCESS = "POST_STOCK_CHECK_SUCCESS";
export const POST_STOCK_CHECK_FAIL = "POST_STOCK_CHECK_FAIL";
export const REMOVE_STOCK_CHECK_DATA = "REMOVE_STOCK_CHECK_DATA";

export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAIL = "POST_ORDER_FAIL";
export const REMOVE_ORDER_DATA = "REMOVE_ORDER_DATA";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const SET_ORDER_INFO = "SET_ORDER_INFO";
export const REMOVE_ORDER_INFO = "REMOVE_ORDER_INFO";
