export const POST_STOCK_CHECK_REQUEST = "POST_STOCK_CHECK_REQUEST";
export const POST_STOCK_CHECK_SUCCESS = "POST_STOCK_CHECK_SUCCESS";
export const POST_STOCK_CHECK_FAIL = "POST_STOCK_CHECK_FAIL";
export const REMOVE_STOCK_CHECK_DATA = "REMOVE_STOCK_CHECK_DATA";

export const SET_ORDER_INFO = "SET_ORDER_INFO";
