export const POST_LOGIN_REQUEST = "POST_LOGIN_REQUEST";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAIL = "POST_LOGIN_FAIL";
export const REMOVE_LOGIN_DATA = "REMOVE_LOGIN_DATA";

export const GET_LOGOUT_REQUEST = "GET_LOGOUT_REQUEST";
export const GET_LOGOUT_SUCCESS = "GET_LOGOUT_SUCCESS";
export const GET_LOGOUT_FAIL = "GET_LOGOUT_FAIL";

export const GET_AUTH_REQUEST = "GET_AUTH_REQUEST";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS";
export const GET_AUTH_FAIL = "GET_AUTH_FAIL";
export const REMOVE_AUTH_DATA = "REMOVE_AUTH_DATA";

export const POST_EMAIL_CHECK_REQUEST = "POST_EMAIL_CHECK_REQUEST";
export const POST_EMAIL_CHECK_SUCCESS = "POST_EMAIL_CHECK_SUCCESS";
export const POST_EMAIL_CHECK_FAIL = "POST_EMAIL_CHECK_FAIL";
export const REMOVE_EMAIL_CHECK_DATA = "REMOVE_EMAIL_CHECK_DATA";

export const POST_REGISTER_REQUEST = "POST_REGISTER_REQUEST";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAIL = "POST_REGISTER_FAIL";
export const REMOVE_REGISTER_DATA = "REMOVE_REGISTER_DATA";
